version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  video-processing:
    lang: python3-flask
    handler: ./video-processing
    image: rikesh64/video-processing:latest
    environment:
      read_timeout: 20m
      write_timeout: 20m
      exec_timeout: 20m
      handler_wait_duration_secs: 21m
      healthcheck_interval: 5s

